# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-02 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(db_tablespace=None, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, db_tablespace=None),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(db_tablespace=None, default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(db_tablespace=None, default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
