# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-16 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.AutoField(auto_created=True, db_tablespace=None, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_tablespace=None, max_length=14, unique=True)),
                ('code', models.CharField(db_tablespace=None, max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, db_tablespace=None, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_tablespace=None, max_length=255, unique=True)),
                ('capital', models.CharField(db_tablespace=None, max_length=255)),
                ('population', models.PositiveIntegerField(db_tablespace=None)),
                ('area', models.PositiveIntegerField(db_tablespace=None)),
                ('code', models.CharField(db_tablespace=None, max_length=2, unique=True)),
                ('continent', models.ForeignKey(db_tablespace=None, on_delete=django.db.models.deletion.CASCADE, to='countrydata.Continent')),
            ],
        ),
    ]
