# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-16 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrydata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='continent',
            name='code',
            field=models.CharField(db_tablespace=None, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='continent',
            name='name',
            field=models.CharField(db_tablespace=None, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(db_tablespace=None, max_length=8, unique=True),
        ),
    ]
