# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-16 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countrydata', '0003_auto_20170216_1530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name']},
        ),
    ]
