# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-16 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countrydata', '0004_auto_20170216_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(db_tablespace=None, on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='countrydata.Continent'),
        ),
    ]
